version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
    restart: unless-stopped
    container_name: mastercrm-frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
